name: tama

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.13
  - pymeep=1.34.0=mpi_mpich_*
  - mpi4py=4.1.2
  - mpich=4.3.2
  - cxx-compiler
  - cmake>=3.20
  - ninja
  - scikit-build-core>=1.0
  - gsl
  - pip
  - autograd
  - numpy
  - scipy
  - nlopt
  - matplotlib
  - pytest
